spring.application.name=demo
spring.datasource.username=admin
spring.datasource.password=StEHUhlf#$%^&8543
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8080

spring.datasource.url=jdbc:mysql://cpproxy-new123.proxy-cl84q2gowr55.ap-south-1.rds.amazonaws.com:3306/customer_portal?useSSL=true&requireSSL=true&verifyServerCertificate=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
spring.datasource.ssl=true
spring.datasource.ssl-mode=VERIFY_IDENTITY
spring.datasource.ssl-ca=classpath:certs/rds-ca-bundle.pem